# Generated by Django 4.0.4 on 2022-04-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'PYTHON'), ('c++', 'C++')], default='c++', max_length=10)),
                ('code', models.TextField()),
                ('testcase', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'PYTHON'), ('c++', 'C++')], default='c++', max_length=10)),
                ('code', models.TextField()),
                ('testcase', models.TextField()),
            ],
        ),
    ]
