# Generated by Django 4.0.4 on 2022-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('c++', 'C++'), ('python', 'Python')], default='c++', max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='language',
            field=models.CharField(choices=[('c++', 'C++'), ('python', 'Python')], default='c++', max_length=10),
        ),
    ]
