# Generated by Django 4.0.4 on 2022-04-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_input_delete_source_delete_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='source_lang',
            new_name='source_language',
        ),
    ]
