# Generated by Django 4.0.4 on 2022-04-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0004_rename_source_lang_input_source_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='target_code',
            field=models.TextField(blank=True),
        ),
    ]
