# Generated by Django 4.0.4 on 2022-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0005_alter_input_target_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='target_code',
            new_name='translated_code',
        ),
    ]
