# Generated by Django 4.0.4 on 2022-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0006_rename_target_code_input_translated_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='target_language',
            field=models.CharField(choices=[('c++', 'C++'), ('python', 'Python')], default='python', max_length=10),
        ),
    ]
