# Generated by Django 4.0.4 on 2022-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0007_alter_input_target_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='source_language',
            field=models.CharField(choices=[('C++', 'C++'), ('Python', 'Python')], default='c++', max_length=10),
        ),
        migrations.AlterField(
            model_name='input',
            name='target_language',
            field=models.CharField(choices=[('C++', 'C++'), ('Python', 'Python')], default='python', max_length=10),
        ),
    ]
